import numpy as np
import random
print(np.array([random.random() for i in range(10)]))
print(np.random.sample())
print(np.random.sample(3))
print(np.random.sample((2, 3)))
print(np.random.randint(0, 3, 10))
print(np.random.random_integers(0, 3, 10))
print(np.random.randint(0, 3, (2, 6)))
print(np.random.uniform(2, 8, (2, 10)))
a = np.arange(10)
np.random.shuffle(a)
print(a)
b = np.arange(10)
print(np.random.permutation(b))
print(b)
print(np.random.permutation(10))
c = np.arange(10)
print(np.random.choice(c, 4, False, [0.25, 0.25, 0.25, 0.25, 0, 0, 0, 0, 0, 0]))
np.random.seed(100)
d = np.random.random(10)
print(d)
np.random.seed(100)
state = np.random.get_state()
e = np.random.random(10)
print(e)
np.random.set_state(state)
f = np.random.random(10)
print(f)